name: Python package CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Display Python version
        run: python -V

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  train_model:
    runs-on: ubuntu-latest
    # container: docker://dvcorg/cml-py3:latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train model
        run: python model.py

      - name: Generate model report
        run: |
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          # cml-publish model_results.png --md >> report.md
          # cml-send-comment report.md
